[project]
name = "cats-dogs-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "tensorboard>=2.21.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
cats-dogs-classification = "cats_dogs_classification:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
